### ISSUE TITLE
block only domain addresses

### ISSUE THREAD

**Issue by Jessar1994** [mike-koch/Mods-for-HESK#477]
When i will block a email address in hesk (@breckliving.com) i get error:
Please, enter a valid email address

Can i only ban the "complete" email addresses?

**Comment by mike-koch** [comment]
The client-side validator is set to "email" I believe, which requires a full email address. I'll fix this in 2.6.0, but in the meantime, you can fix it by changing `type="email"` to `type="text"` at https://github.com/mike-koch/Mods-for-HESK/blob/master/admin/banned_emails.php#L133

**Comment by Jessar1994** [comment]
Thanks! :)
